/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'customerName' : [] | [string],
  'paymentStatus' : PaymentStatus,
  'customerPhone' : [] | [string],
  'totalAmount' : bigint,
  'billNumber' : string,
  'timestamp' : Time,
  'generatedByAdmin' : Principal,
  'paymentReference' : [] | [string],
  'items' : Array<BillItem>,
  'paymentGatewayId' : [] | [string],
}
export interface BillItem {
  'productId' : bigint,
  'productName' : string,
  'pricePerUnit' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
}
export interface CartItem { 'quantity' : bigint, 'product' : Product }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'timestamp' : Time,
  'phoneNumber' : string,
  'products' : Array<Product>,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'out_for_delivery' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'packed' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface Product {
  'id' : bigint,
  'unitType' : UnitType,
  'name' : string,
  'barcode' : string,
  'category' : string,
  'image' : ExternalBlob,
  'priceInRupees' : bigint,
}
export interface ProductWithAction { 'action' : string, 'product' : Product }
export interface RechargeOrder {
  'id' : bigint,
  'rechargeAmount' : bigint,
  'operator' : string,
  'mobileNumber' : string,
}
export type Time = bigint;
export type UnitType = { 'kg' : null } |
  { 'gram' : null } |
  { 'piece' : null } |
  { 'packet' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, ExternalBlob, string, UnitType],
    bigint
  >,
  'addProductByBarcode' : ActorMethod<[string, bigint], ProductWithAction>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotalPrice' : ActorMethod<[bigint], bigint>,
  'clearCart' : ActorMethod<[], undefined>,
  'confirmOrder' : ActorMethod<[bigint], undefined>,
  'generateBill' : ActorMethod<
    [[] | [string], [] | [string], Array<BillItem>, bigint],
    Bill
  >,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllRechargeOrders' : ActorMethod<[], Array<RechargeOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getExcludedProducts' : ActorMethod<[], Array<bigint>>,
  'getProductByBarcode' : ActorMethod<[string], [] | [Product]>,
  'getProductByBarcodeWithAction' : ActorMethod<[string], ProductWithAction>,
  'getShopSlogan' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsCompleted' : ActorMethod<[bigint], undefined>,
  'markAsOutForDelivery' : ActorMethod<[bigint], undefined>,
  'markAsPacked' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<
    [string, string, string, bigint, PaymentMethod],
    bigint
  >,
  'placeRechargeOrder' : ActorMethod<[string, string, bigint], bigint>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setShopSlogan' : ActorMethod<[string], undefined>,
  'toggleProductExclusion' : ActorMethod<[bigint], boolean>,
  'updateBillPaymentStatus' : ActorMethod<
    [bigint, PaymentStatus, [] | [string], [] | [string]],
    Bill
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];