/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UnitType = IDL.Variant({
  'kg' : IDL.Null,
  'gram' : IDL.Null,
  'piece' : IDL.Null,
  'packet' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'unitType' : UnitType,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'priceInRupees' : IDL.Nat,
});
export const ProductWithAction = IDL.Record({
  'action' : IDL.Text,
  'product' : Product,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'pricePerUnit' : IDL.Nat,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Opt(IDL.Text),
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'billNumber' : IDL.Text,
  'timestamp' : Time,
  'generatedByAdmin' : IDL.Principal,
  'paymentReference' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(BillItem),
  'paymentGatewayId' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'out_for_delivery' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'packed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'products' : IDL.Vec(Product),
  'totalPrice' : IDL.Nat,
});
export const RechargeOrder = IDL.Record({
  'id' : IDL.Nat,
  'rechargeAmount' : IDL.Nat,
  'operator' : IDL.Text,
  'mobileNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Text, UnitType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addProductByBarcode' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [ProductWithAction],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotalPrice' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'clearCart' : IDL.Func([], [], []),
  'confirmOrder' : IDL.Func([IDL.Nat], [], []),
  'generateBill' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Vec(BillItem), IDL.Nat],
      [Bill],
      [],
    ),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllRechargeOrders' : IDL.Func([], [IDL.Vec(RechargeOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getExcludedProducts' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getProductByBarcode' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductByBarcodeWithAction' : IDL.Func(
      [IDL.Text],
      [ProductWithAction],
      ['query'],
    ),
  'getShopOpenStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getShopSlogan' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsCompleted' : IDL.Func([IDL.Nat], [], []),
  'markAsOutForDelivery' : IDL.Func([IDL.Nat], [], []),
  'markAsPacked' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PaymentMethod],
      [IDL.Nat],
      [],
    ),
  'placeRechargeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'removeProduct' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setShopOpenStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'setShopSlogan' : IDL.Func([IDL.Text], [], []),
  'toggleProductExclusion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateBillPaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Bill],
      [],
    ),
  'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UnitType = IDL.Variant({
    'kg' : IDL.Null,
    'gram' : IDL.Null,
    'piece' : IDL.Null,
    'packet' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'unitType' : UnitType,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'priceInRupees' : IDL.Nat,
  });
  const ProductWithAction = IDL.Record({
    'action' : IDL.Text,
    'product' : Product,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'pricePerUnit' : IDL.Nat,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Opt(IDL.Text),
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'billNumber' : IDL.Text,
    'timestamp' : Time,
    'generatedByAdmin' : IDL.Principal,
    'paymentReference' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(BillItem),
    'paymentGatewayId' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'out_for_delivery' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'packed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cod' : IDL.Null, 'upi' : IDL.Null });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'products' : IDL.Vec(Product),
    'totalPrice' : IDL.Nat,
  });
  const RechargeOrder = IDL.Record({
    'id' : IDL.Nat,
    'rechargeAmount' : IDL.Nat,
    'operator' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          IDL.Text,
          UnitType,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'addProductByBarcode' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [ProductWithAction],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotalPrice' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'clearCart' : IDL.Func([], [], []),
    'confirmOrder' : IDL.Func([IDL.Nat], [], []),
    'generateBill' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Vec(BillItem), IDL.Nat],
        [Bill],
        [],
      ),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllRechargeOrders' : IDL.Func([], [IDL.Vec(RechargeOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getExcludedProducts' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getProductByBarcode' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductByBarcodeWithAction' : IDL.Func(
        [IDL.Text],
        [ProductWithAction],
        ['query'],
      ),
    'getShopOpenStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getShopSlogan' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsCompleted' : IDL.Func([IDL.Nat], [], []),
    'markAsOutForDelivery' : IDL.Func([IDL.Nat], [], []),
    'markAsPacked' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'placeRechargeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'removeProduct' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setShopOpenStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'setShopSlogan' : IDL.Func([IDL.Text], [], []),
    'toggleProductExclusion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateBillPaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Bill],
        [],
      ),
    'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };